import { useState, useEffect } from 'react';
import API from '../api/axios';
import jsPDF from 'jspdf';

const Report = () => {
  const [report, setReport] = useState('');
  const [loading, setLoading] = useState(true);
  const sessionId = localStorage.getItem('sessionId');

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await API.post('/report/generate', { sessionId });
        setReport(res.data.report);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, []);

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(124, 58, 237);
    doc.text('AI Interview Prep — Analysis Report', 20, 20);
    doc.setDrawColor(124, 58, 237);
    doc.line(20, 25, 190, 25);
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    const lines = doc.splitTextToSize(report, 170);
    let y = 35;
    lines.forEach((line) => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(line, 20, y);
      y += 7;
    });
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by AI Interview Prep', 20, 285);
    doc.save('interview-report.pdf');
  };

  const formatReport = (text) => {
    return text.split('\n').map((line, i) => {
      if (line.match(/^\d\./) || line.startsWith('##')) {
        return (
          <p key={i} className="text-violet-700 font-bold text-base mt-6 mb-2 border-l-4 border-violet-400 pl-3">
            {line.replace('##', '').trim()}
          </p>
        );
      }
      if (line.startsWith('**') && line.endsWith('**')) {
        return <p key={i} className="text-gray-800 font-semibold mt-3">{line.replace(/\*\*/g, '')}</p>;
      }
      if (line.startsWith('-') || line.startsWith('•')) {
        return (
          <p key={i} className="text-gray-600 text-sm pl-4 mt-1 flex items-start gap-2">
            <span className="text-violet-400 mt-0.5">•</span>
            {line.replace(/^[-•]/, '').trim()}
          </p>
        );
      }
      if (line.trim() === '') return <div key={i} className="h-2" />;
      return <p key={i} className="text-gray-600 text-sm leading-relaxed mt-1">{line}</p>;
    });
  };

  return (
    <div className="min-h-screen px-6 py-10" style={{ background: 'linear-gradient(180deg, #f5f3ff 0%, #f4f5f7 30%)' }}>
      <div className="max-w-2xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">Interview Report</h2>
            <p className="text-gray-500 text-sm">Your personalized analysis</p>
          </div>
          {!loading && (
            <button
              onClick={handleDownloadPDF}
              className="btn-primary px-5 py-2.5 rounded-xl font-medium text-sm"
            >
              ⬇️ Download PDF
            </button>
          )}
        </div>

        {loading ? (
          <div className="card p-16 text-center">
            <div className="w-12 h-12 border-2 border-violet-200 border-t-violet-600 rounded-full animate-spin mx-auto mb-4" />
            <p className="text-gray-600 font-medium">Generating your report...</p>
            <p className="text-gray-400 text-sm mt-1">This may take a few seconds</p>
          </div>
        ) : (
          <div className="card p-8">
            <div>{formatReport(report)}</div>
            <div className="flex gap-3 mt-8 pt-6 border-t border-gray-100">
              <button
                onClick={handleDownloadPDF}
                className="btn-primary px-6 py-3 rounded-xl font-medium"
              >
                ⬇️ Download PDF
              </button>
              <button
                onClick={() => window.print()}
                className="bg-gray-100 hover:bg-gray-200 text-gray-600 px-6 py-3 rounded-xl font-medium transition-all"
              >
                🖨️ Print
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Report;